from __future__ import annotations

from enum import StrEnum


MEMORY_CONTRACT_VERSION = "1.0"
SCHEMA_VERSION = 3


class MemoryNamespace(StrEnum):
    OWNER = "OWNER"
    JARVIS = "JARVIS"
    SYSTEM = "SYSTEM"
    PROJECT = "PROJECT"
    PERSON = "PERSON"
    DEVICE = "DEVICE"
    PLACE = "PLACE"
    ORGANIZATION = "ORGANIZATION"
    EXTERNAL = "EXTERNAL"


class MemoryClass(StrEnum):
    FACTUAL = "FACTUAL"
    RELATIONAL = "RELATIONAL"
    EPISODIC = "EPISODIC"
    PROCEDURAL = "PROCEDURAL"
    PREFERENCE = "PREFERENCE"
    GOAL = "GOAL"
    CONSTRAINT = "CONSTRAINT"
    OBSERVATION = "OBSERVATION"
    INFERENCE = "INFERENCE"
    SYSTEM_STATE = "SYSTEM_STATE"
    PROJECT = "PROJECT"


class MemoryAuthority(StrEnum):
    OWNER_EXPLICIT = "OWNER_EXPLICIT"
    OWNER_CONFIRMED = "OWNER_CONFIRMED"
    DIRECT_TOOL_OBSERVATION = "DIRECT_TOOL_OBSERVATION"
    SYSTEM_OBSERVATION = "SYSTEM_OBSERVATION"
    TRUSTED_LOCAL_SOURCE = "TRUSTED_LOCAL_SOURCE"
    PROJECT_SOURCE = "PROJECT_SOURCE"
    DOCUMENT_SOURCE = "DOCUMENT_SOURCE"
    CONVERSATION_DERIVED = "CONVERSATION_DERIVED"
    MODEL_INFERRED = "MODEL_INFERRED"
    EXTERNAL_SOURCE = "EXTERNAL_SOURCE"
    MIGRATED_LEGACY = "MIGRATED_LEGACY"


class SourceType(StrEnum):
    OWNER_TURN = "OWNER_TURN"
    JARVIS_TURN = "JARVIS_TURN"
    TOOL_RESULT = "TOOL_RESULT"
    SYSTEM_EVENT = "SYSTEM_EVENT"
    PROJECT_EVENT = "PROJECT_EVENT"
    DOCUMENT = "DOCUMENT"
    WEB = "WEB"
    HOME_ASSISTANT = "HOME_ASSISTANT"
    MIGRATION = "MIGRATION"
    INTERNAL_DERIVATION = "INTERNAL_DERIVATION"


class MemoryStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    EXPIRED = "EXPIRED"
    CONFLICTED = "CONFLICTED"
    FORGOTTEN = "FORGOTTEN"
    QUARANTINED = "QUARANTINED"
    RETRACTED = "RETRACTED"


class ValueType(StrEnum):
    STRING = "STRING"
    INTEGER = "INTEGER"
    FLOAT = "FLOAT"
    BOOLEAN = "BOOLEAN"
    DATE = "DATE"
    DATETIME = "DATETIME"
    DURATION = "DURATION"
    ENTITY_REF = "ENTITY_REF"
    QUANTITY = "QUANTITY"
    ENUM = "ENUM"
    JSON = "JSON"


class Cardinality(StrEnum):
    SINGLE_CURRENT = "SINGLE_CURRENT"
    MULTI_CURRENT = "MULTI_CURRENT"
    TEMPORAL_SINGLE = "TEMPORAL_SINGLE"
    TEMPORAL_MULTI = "TEMPORAL_MULTI"
    UNBOUNDED = "UNBOUNDED"


class CommitStatus(StrEnum):
    COMMITTED = "COMMITTED"
    REJECTED = "REJECTED"
    CONFLICT_REQUIRES_CONFIRMATION = (
        "CONFLICT_REQUIRES_CONFIRMATION"
    )
    NO_CHANGE = "NO_CHANGE"


class AuditEventType(StrEnum):
    ENTITY_CREATED = "ENTITY_CREATED"
    PROPERTY_CREATED = "PROPERTY_CREATED"
    EPISODE_RECORDED = "EPISODE_RECORDED"
    PROPOSAL_RECEIVED = "PROPOSAL_RECEIVED"
    PROPOSAL_ACCEPTED = "PROPOSAL_ACCEPTED"
    PROPOSAL_REJECTED = "PROPOSAL_REJECTED"
    FACT_CREATED = "FACT_CREATED"
    RELATION_CREATED = "RELATION_CREATED"
    FACT_SUPERSEDED = "FACT_SUPERSEDED"
    RELATION_SUPERSEDED = "RELATION_SUPERSEDED"
    CONFLICT_DETECTED = "CONFLICT_DETECTED"
    FORGOTTEN = "FORGOTTEN"
    PURGED = "PURGED"
    MIGRATED = "MIGRATED"
    QUARANTINED = "QUARANTINED"
    QUERY_EXECUTED = "QUERY_EXECUTED"
    PROJECTION_APPLIED = "PROJECTION_APPLIED"
    PROJECTION_FAILED = "PROJECTION_FAILED"
    TRANSACTION_COMMITTED = "TRANSACTION_COMMITTED"

class PropertyKind(StrEnum):
    FACT = "FACT"
    RELATION = "RELATION"


class TransactionStatus(StrEnum):
    IN_PROGRESS = "IN_PROGRESS"
    COMMITTED = "COMMITTED"
